from enum import Enum

class MBR(Enum):
	START_PROTECT = 444
	END_PROTECT = 446
	START_PART1 = 446
	END_PART1 = 462
	START_PART2 = 462
	END_PART2 = 478
	START_PART3 = 478
	END_PART3 = 494
	START_PART4 = 494
	END_PART4 = 510
	START_SIGNATUREF = 510
	END_SIGNATUREF = 512

class Type(Enum):
	FAT12 = (1, "FAT12")
	FAT16CHS = (6, "FAT16CHS")
	FAT32CHS = (11, "FAT32CHS")

	@classmethod
	def listType(self):
		return [self.FAT12, self.FAT16CHS, self.FAT32CHS]

	@classmethod
	def get_type(self,code):
		listT = self.listType()
		for t in listT:
			if code == t[0]:
				return t

class Part_MBR(Enum):
	START_STATUS = 0 
	END_STATUS = 1
	START_CHS_FIST_SECTOR = 1
	END_CHS_FIST_SECTOR = 4
	START_TYPE = 4
	END_TYPE = 5
	START_CHS_LAST_SECTOR = 5
	END_CHS_LAST_SECTOR = 8
	START_LBA_FIRST_SECTOR = 8
	END_LBA_FIRST_SECTOR = 12
	START_QTT_SECTOR = 12
	END_QTT_SECTOR = 16

class FAT(Enum):
	START_BOOT = 0
	END_BOOT = 3
	START_DESC_FAB = 3
	END_DESC_FAB = 11
	START_BYTES_SECTOR = 11
	END_BYTES_SECTOR = 13
	START_SECTOR_CLUSTER = 13
	END_SECTOR_CLUSTER = 14
	START_RESERVED_SECTORS = 14
	END_RESERVED_SECTOR = 16
	START_QTT_ALOC_TABLE = 16
	END_QTT_ALOC_TABLE = 17
	START_ENTRY_ROOT = 17
	END_ENTRY_ROOT = 19
	START_QTT_SECTOR = 19
	END_QTT_SECTOR = 21
	STAR_DESC_MEDIA = 21
	END_DESC_MEDIA = 22
	START_QTT_SECTOR_ALOC_TABLE = 22
	END_QTT_SECTOR_ALOC_TABLE = 24
	START_SIGNATURE = 510
	END_SIGNATURE = 512
