#!/usr/bin/python3

from enum import IntEnum,Enum

class FAT_RESERVED(IntEnum):
    START_BOOT = 0
    END_BOOT = 3
    START_DESC_FAB = 3
    END_DESC_FAB = 11
    START_BYTES_SECTOR = 11
    END_BYTES_SECTOR = 13
    START_SECTOR_CLUSTER = 13
    END_SECTOR_CLUSTER = 14
    START_RESERVED_SECTORS = 14
    END_RESERVED_SECTORS = 16
    START_QTT_ALOC_TABLE = 16
    END_QTT_ALOC_TABLE = 17
    START_QTT_ROOT_ENTRY = 17
    END_QTT_ROOT_ENTRY = 19
    STAR_DESC_MEDIA = 21
    END_DESC_MEDIA = 22


class FAT_ALOC_TABLE(IntEnum):
    START_FILE_NAME = 0
    END_FILE_NAME = 8
    START_EXT_FILE = 8
    END_EXT_FILE = 11
    START_FIRST_CLUSTER = 26
    END_FIRST_CLUSTER = 28
    START_FILE_SIZE = 28
    END_FILE_SIZE = 32