from enum import Enum, IntEnum

class FAT32_RESERVED(IntEnum):
    START_FIRST_ROOT_CLUSTER = 44
    END_FIRST_ROOT_CLUSTER = 48
    START_QTT_SECTOR_ALOC_TABLE = 36
    END_QTT_SECTOR_ALOC_TABLE = 40